#!/bin/bash

cd /SHV/shvapp/bin
LD_LIBRARY_PATH=../lib ./shvbroker --config-dir ../shvbroker/etc/shv/shvbroker/ -v rpcmsg & 
cd /SHV/shvspy/bin
LD_LIBRARY_PATH=../lib/ ./shvspy -v rpcmsg 

killall shvbroker

